platform :ios, '10.3'

inhibit_all_warnings!
use_frameworks!

target 'Menuator_Example' do
    pod 'Menuator', :path => '../'
    pod 'SnapKit', '~> 4.0.0'
    
    target 'Menuator_Tests' do
        inherit! :search_paths

        pod 'SpecTools', '~> 1.0.2'
        pod 'Quick'
        pod 'Nimble'
    end
end
